import {
  Add,
  Check,
  Close,
  DataObject,
  Delete,
  Edit,
  ExpandMore,
  Folder,
  GridOn,
  InsertDriveFile,
  Lan,
  Language,
  MoreVert,
  ReplayCircleFilled,
  UploadFile,
  ViewList,
} from "@mui/icons-material";

export const Icons = {
  ApiDocs: DataObject,
  Language: Language,
  ExpandChevron: ExpandMore,
  List: ViewList,
  Grid: GridOn,
  Network: Lan,
  FileItem: InsertDriveFile,
  Files: Folder,
  Delete: Delete,
  Rename: Edit,
  Confirm: Check,
  Cancel: Close,
  Add: Add,
  MoreContext: MoreVert,
  Replays: ReplayCircleFilled,
  UploadFile: UploadFile,
};
