import {
  Add,
  AllInclusive,
  Block,
  Check,
  Close,
  DataObject,
  Delete,
  Done,
  Edit,
  ExpandMore,
  FastForward,
  FileDownload,
  Folder,
  FormatListBulletedAdd,
  GridOn,
  Help,
  HourglassTop,
  InfoOutline,
  InputRounded,
  InsertDriveFile,
  Lan,
  Language,
  Loop,
  MoreVert,
  Numbers,
  Output,
  PlayArrow,
  PlaylistAdd,
  PlaylistPlay,
  PriorityHigh,
  RepeatOne,
  ReplayCircleFilled,
  ShortText,
  Signpost,
  Speed,
  SportsScore,
  Stop,
  SwapHoriz,
  SwapVert,
  Timer,
  Tune,
  UploadFile,
  ViewColumn,
  ViewList,
} from "@mui/icons-material";

export const Icons = {
  About: Help,
  ApiDocs: DataObject,
  Language: Language,
  Name: ShortText,
  ExpandChevron: ExpandMore,
  List: ViewList,
  Grid: GridOn,
  SelectColumn: ViewColumn,
  Network: Lan,
  FileAddToJob: PlaylistAdd,
  FileItem: InsertDriveFile,
  Files: Folder,
  Delete: Delete,
  Rename: Edit,
  Confirm: Check,
  Cancel: Close,
  Add: Add,
  Edit: Edit,
  MoreContext: MoreVert,
  Replays: ReplayCircleFilled,
  Infinity: AllInclusive,
  RepeatTimes: RepeatOne,
  Loop: Loop,
  LoadLimit: HourglassTop,
  Duration: Timer,
  Numbers: Numbers,
  Speed: FastForward,
  SpeedMult: Tune,
  SpeedDataRate: Speed,
  SpeedPackets: SwapVert,
  PortRemap: SwapHoriz,
  AddressRemap: Signpost,
  Forbidden: Block,
  UploadFile: UploadFile,
  DownloadFile: FileDownload,
  Source: InputRounded,
  Destination: Output,
  Status: InfoOutline,
  Created: FormatListBulletedAdd,
  Started: PlaylistPlay,
  Finished: SportsScore,
  StatusStopped: Stop,
  StatusRunning: PlayArrow,
  StatusError: PriorityHigh,
  StatusFinished: Done,
};
