import {
  Add,
  AllInclusive,
  Block,
  Check,
  Close,
  DataObject,
  Delete,
  Edit,
  ExpandMore,
  FastForward,
  FileDownload,
  Folder,
  GridOn,
  HourglassTop,
  InsertDriveFile,
  Lan,
  Language,
  Loop,
  MoreVert,
  Numbers,
  PlaylistAdd,
  RepeatOne,
  ReplayCircleFilled,
  Signpost,
  Speed,
  SwapHoriz,
  SwapVert,
  Timer,
  Tune,
  UploadFile,
  ViewList,
} from "@mui/icons-material";

export const Icons = {
  ApiDocs: DataObject,
  Language: Language,
  ExpandChevron: ExpandMore,
  List: ViewList,
  Grid: GridOn,
  Network: Lan,
  FileAddToJob: PlaylistAdd,
  FileItem: InsertDriveFile,
  Files: Folder,
  Delete: Delete,
  Rename: Edit,
  Confirm: Check,
  Cancel: Close,
  Add: Add,
  Edit: Edit,
  MoreContext: MoreVert,
  Replays: ReplayCircleFilled,
  Infinity: AllInclusive,
  RepeatTimes: RepeatOne,
  Loop: Loop,
  LoadLimit: HourglassTop,
  Duration: Timer,
  Numbers: Numbers,
  Speed: FastForward,
  SpeedMult: Tune,
  SpeedDataRate: Speed,
  SpeedPackets: SwapVert,
  PortRemap: SwapHoriz,
  AddressRemap: Signpost,
  Forbidden: Block,
  UploadFile: UploadFile,
  DownloadFile: FileDownload,
};
