name: Cleanup images of closed pull-request

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Find version ID for PR
        id: find_version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION_IDS=$(gh api -H "Accept: application/vnd.github+json" \
          /user/packages/container/${{ github.event.repository.name }}/versions \
          | jq -r ".[] | select(.metadata.container.tags | any(. == \"pr-${{ github.event.pull_request.number }}\")) | .id" \
          | paste -sd, -)

          if [[ -z "$VERSION_IDS" ]]; then
            echo "No image found for PR tag pr-${{ github.event.pull_request.number }}"
            exit 0
          fi

          echo "VERSION_IDS=$VERSION_IDS" >> $GITHUB_OUTPUT

      - name: Delete PR image
        if: ${{ steps.find_version.outputs.VERSION_IDS != '' }}
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ github.event.repository.name }}
          package-type: container
          package-version-ids: ${{ steps.find_version.outputs.VERSION_IDS }}
