name: Build pull-request image

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  pre-checks:
    uses: ./.github/workflows/pre-checks.yml

  build:
    needs: pre-checks
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ghcr.io/${{ github.repository }}:pr-${{ github.event.pull_request.number }}
          outputs: type=docker,dest=/tmp/${{ github.event.repository.name }}-pr-${{ github.event.pull_request.number }}.tar

      - uses: actions/upload-artifact@v4
        with:
          path: /tmp/${{ github.event.repository.name }}-pr-${{ github.event.pull_request.number }}.tar
